language: rust
rust:
  - stable
  - beta
  - nightly
matrix:
  allow_failures:
    - rust: nightly
script:
  - cargo build --verbose
  - cargo test --verbose
  - cd tests
  - cmake -DEDITORCONFIG_CMD=`pwd`/../target/debug/editorconfig -E $(cat ../test_skip_regex.txt) .
  - ctest .
